---
- hosts: all
  connection: local
  become: yes
  
  tasks:
    - name: Install epel-release
      yum:
          name: epel-release

    - name: Install varnish packages
      yum:
          name: varnish

    - name: start varnish service
      service:
          name: varnish
          state: running
          enabled: yes
